create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  answers jsonb not null,
  score integer not null check (score between 0 and 72),
  max_score integer not null default 72,
  percentage numeric(5, 2) not null,
  predicted_label text,
  adhd_probability numeric(6, 4),
  top_factors jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.assessments enable row level security;

drop policy if exists "Users can view their own assessments" on public.assessments;
create policy "Users can view their own assessments"
  on public.assessments for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own assessments" on public.assessments;
create policy "Users can insert their own assessments"
  on public.assessments for insert
  with check (auth.uid() = user_id);